import { Injectable, NotFoundException } from '@nestjs/common'; import { PrismaService } from '../prisma/prisma.service';
@Injectable() export class ContactsService {
    constructor(private db: PrismaService) { }
    list(companyId: string, q?: string, status?: any) { return this.db.contact.findMany({ where: { companyId, status, ...q ? { OR: [{ firstName: { contains: q, mode: 'insensitive' } }, { lastName: { contains: q, mode: 'insensitive' } }, { phone: { contains: q } }, { email: { contains: q, mode: 'insensitive' } }] } : {} }, include: { tags: { include: { tag: true } } }, orderBy: { createdAt: 'desc' } }) }
    create(companyId: string, b: any, userId: string) { return this.db.$transaction(async tx => { const c = await tx.contact.create({ data: { companyId, firstName: b.firstName, lastName: b.lastName, phone: b.phone, email: b.email, status: b.status, source: b.source, customFields: b.customFields } }); await tx.activityLog.create({ data: { companyId, contactId: c.id, userId, type: 'CONTACT_CREATED' } }); return c }) }
    async update(companyId: string, id: string, b: any, userId: string) { const old = await this.db.contact.findFirst({ where: { id, companyId } }); if (!old) throw new NotFoundException(); const c = await this.db.contact.update({ where: { id }, data: b }); await this.db.activityLog.create({ data: { companyId, contactId: id, userId, type: 'CONTACT_UPDATED', metadata: b } }); return c }
    async consent(companyId: string, id: string, type: 'OPT_IN' | 'OPT_OUT', source?: string) { const c = await this.db.contact.findFirst({ where: { id, companyId } }); if (!c) throw new NotFoundException(); return this.db.consentLog.create({ data: { companyId, contactId: id, type: type.toLowerCase(), source } }) }
    async addTag(companyId: string, id: string, tagId: string) { const c = await this.db.contact.findFirst({ where: { id, companyId } }); if (!c) throw new NotFoundException(); const t = await this.db.tag.findFirst({ where: { id: tagId, companyId } }); if (!t) throw new NotFoundException(); return this.db.contactTag.upsert({ where: { contactId_tagId: { contactId: id, tagId } }, create: { contactId: id, tagId }, update: {} }) }
}
